### ISSUE TITLE
[LineageOS-17.1] Current issues

### ISSUE THREAD

**Issue by SamarV-121** [SamarV-121/android_device_samsung_universal7904-common#1]
- 3rd camera - [Need this patch](https://github.com/phhusson/platform_frameworks_av/commit/74704affac464858eb42ba32e6ad45df3e4dfe70) 
[`dumpsys media.camera` - 3rd camera id is 52](https://gist.github.com/SamarV-121/27b98ccd4cfb4dae67295f6187b44f45)
- [~~Bluetooth calls~~](https://github.com/SamarV-121/android_device_samsung_universal7904-common/search?q=bt&type=commits)
- [~~NFC~~](https://github.com/SamarV-121/android_device_samsung_universal7904-common/search?q=nfc&type=commits)
- [~~USB audio~~](https://github.com/SamarV-121/android_device_samsung_universal7904-common/commit/b955b20276016132ff05117ad3e9e29d25e3acf5)
- [~~Incorrect video length(video gets lengthened by the exact amount of time that the phone was in deepsleep.)~~](https://github.com/SamarV-121/android_device_samsung_universal7904-common/commit/faae9d490b8e933086889d009427fff5550ecf32)

**Comment by SamarV-121** [comment]
Encryption working with lineage recovery

**Comment by kirnevi** [comment]
When plugged in to charger touch screen reacts slower and strange.

MTP is not working.

**Comment by kirnevi** [comment]
When i record video it makes the video randomly 20, 30 or 90 hours long even if the video 10 seconds is.

**Comment by kirnevi** [comment]
• Rare random restarts (and stucks at boot screen)

**Comment by SamarV-121** [comment]
Never faced both of them 
Give logcat (make sure you dont have any custom modules/kernel installed)

**Comment by SamarV-121** [comment]
and create new issue :3
