### ISSUE TITLE
[M20] [LineageOS18.1] Bug in setting's lock screen 

### ISSUE THREAD

**Issue by u-n-e-s** [SamarV-121/android_device_samsung_universal7904-common#10]
i flashed latest 12/08 rom file, rebooted skiped wifi but when trying to set a lock patern to process just restarts after pressing "confirm" & return to begening of choosing the lock method.

this is the logcat of the minute where i tried this :
https://drive.google.com/file/d/1-3GJYU6Z8FSNPRJ6ZIMa-qcIxHRE1oBQ/view?usp=sharing

and this file for full log :
https://drive.google.com/file/d/1uFk6m6qUz87fo9PL_DKVslnr9Q1plGSC/view?usp=sharing

**Comment by SamarV-121** [comment]
[PM me on telegram](https://t.me/SamarV121)
