### ISSUE TITLE
Random Actions and Touch Freeze Samsung M20. Not fixed on some devices

### ISSUE THREAD

**Issue by DaHype007** [SamarV-121/android_device_samsung_universal7904-common#12]
Please Hope for fix. Random Actions, Touch not Respond.
Samsung M20

Time in Logcat:

 21:19 Massive Random Actions 
21:30 Touch after Wakeup not Respond
[logcat.txt](https://github.com/SamarV-121/android_device_samsung_universal7904-common/files/7033684/logcat.txt)

Edit: Sorry, Problems with Sakura not with SamarV...

**Comment by SamarV-121** [comment]
> Please Hope for fix. Random Actions, Touch not Respond.
> Samsung M20
> 
> Time in Logcat:
> 
> 21:19 Massive Random Actions
> 21:30 Touch after Wakeup not Respond
> [logcat.txt](https://github.com/SamarV-121/android_device_samsung_universal7904-common/files/7033684/logcat.txt)

https://t.me/lineage_7904/1749

**Comment by DaHype007** [comment]
Sorry, It was my fault! I  used Lineage 18.1 Mod by Sakura 5.2. There are the massive Problems!

I flashed now your Rom. **There are also Problems with Random Actions and Touch Freeze**, but not so often as in Sakura.

I hope you can improve andd fix it. I will provide an Logcat soon.

Thanks

**Comment by SamarV-121** [comment]
Please follow that template I linked you

**Comment by SamarV-121** [comment]
I don't have such issue btw

**Comment by DaHype007** [comment]
I will provide Logcat soon and i write you than the time when the issue happens.

It seems that´s an Problem of Lineage OS (Vendor??), because on Sakura it´s also based on Lineage and Sakura developer already known about that and they will fix it soon they told.

On your Rom its much better than Sakura, but it happens several times a day.

No Problem of my M20, because i flashed your Rom on 4 M20 devices. Clean Install of course. No Magisk......

I will inform you soon

Thanks for your reply

**Comment by DaHype007** [comment]
First Log Problem from today about Time 15:05

Random Actions and Total Freeze Touch. Solution only to push Wakeup Button off and on again.

I start Phone now new and send you than again an Log when the problem happens.

What is your--
LineageOS version: lineage-18.1-plus-20210811_071647-UNOFFICIAL-c22c410-m20lte.zip
LineageOS Download url: https://samarv-121.github.io/lineageos-18.1-m20lte/
Gapps version: NikGapps-full-arm64-11-20201231-signed (But happens also without Gapps)

Did you--
wipe: Clean Install
restore with titanium backup/migrate: NO
reboot after having the issue: Yes several times

Are you using--
a task killer: NO
a custom kernel: NO
a magisk module: NO
other modifications: NO
[logcat.txt](https://github.com/SamarV-121/android_device_samsung_universal7904-common/files/7047415/logcat.txt)

**Comment by DaHype007** [comment]
Touch Screen Freeze, no respond. Only after Wakeup Button Off/On works again.

Time: 08:12 and 08:24

[logcat.txt](https://github.com/SamarV-121/android_device_samsung_universal7904-common/files/7056085/logcat.txt)


Seems  the most problems with Touch and Random Actions shown DeadZone in Log.


Another Log 13:02 Time. Start with Random Action and ends in Total Screen Freeze.

[logcat.txt](https://github.com/SamarV-121/android_device_samsung_universal7904-common/files/7057232/logcat.txt)

I hope it will help you to get fix that problems.
Thanks for your work

**Comment by SamarV-121** [comment]
> Touch Screen Freeze, no respond. Only after Wakeup Button Off/On works again.
> 
> Time: 08:12 and 08:24
> 
> [logcat.txt](https://github.com/SamarV-121/android_device_samsung_universal7904-common/files/7056085/logcat.txt)
> 
> Seems the most problems with Touch and Random Actions shown DeadZone in Log.
> 
> Another Log 13:02 Time. Start with Random Action and ends in Total Screen Freeze.
> 
> [logcat.txt](https://github.com/SamarV-121/android_device_samsung_universal7904-common/files/7057232/logcat.txt)
> 
> I hope it will help you to get fix that problems.
> Thanks for your work

PM me on [telegram](http://t.me/SamarV121)

**Comment by DaHype007** [comment]
Not fixed, but i don´´t have much time now to make  Logcat. Only work fine with older Kernel (boot.im) from June!

Than no problems. Also confirmed from another User here:

https://forum.xda-developers.com/t/lineageos-18-1-plus-for-samsung-galaxy-m20-by-samar-vispute.4333517/post-85634591

He also have the massive Problems
