### ISSUE TITLE
A couple of bugs

### ISSUE THREAD

**Issue by kirnevi** [SamarV-121/android_device_samsung_universal7904-common#2]
When plugged in to charger touch screen reacts slower and strange.

MTP is not working.

**Comment by SamarV-121** [comment]
seems fine here while charging 
and MTP is working too

**Comment by kirnevi** [comment]
> seems fine here while charging
> and MTP is working too

Should i flash anything out of the rom zip for the mtp (Fuse kernel, phix.zip etc.)?
I ll try with another charger to see if it's a charger problem :)

**Comment by SamarV-121** [comment]
No

**Comment by paulocavallari** [comment]
Mtp only works for my with fuse kernel

**Comment by SamarV-121** [comment]
@paulocavallari @kirnevi Turn off USB debugging and try MTP
it'll work fine
