### ISSUE TITLE
not working nfc

### ISSUE THREAD

**Issue by advokat11** [SamarV-121/android_device_samsung_universal7904-common#3]
nfc icon is grey in status bar and my app don't see nfc
![photo_2020-09-15_23-08-57](https://user-images.githubusercontent.com/59486045/93259402-78b64900-f7a8-11ea-97fa-44fdf457a847.jpg)
SM-M205FN
Nothing about nfc in settings.

**Comment by kirnevi** [comment]
This phone doesn't have nfc brother it's a null function from the ROM :)

**Comment by SamarV-121** [comment]
Fixed in [lineage-17.1-20200921-UNOFFICIAL-m20lte.zip](https://github.com/SamarV-121/releases/releases/download/lineage-17.1-20200921-UNOFFICIAL-m20lte-1106/lineage-17.1-20200921-UNOFFICIAL-m20lte.zip)

**Comment by SamarV-121** [comment]
@kirnevi european varient does have NFC :3
